---
- name: Install Apache2
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        lock_timeout: 120 
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

